### ISSUE TITLE
Acuity and range of senses

### ISSUE THREAD

**Issue by TheAsel** [RakuJa/BYBE-DB#10]
The fields for "acuity" and "range" of senses isn't parsed. This is especially relevant for "scent", as that information can't be retrieved from anywhere else. An example of this is [Mengkare](https://github.com/foundryvtt/pf2e/blob/master/packs/age-of-ashes-bestiary/mengkare.json).

**Comment by RakuJa** [comment]
Duplicate of https://github.com/RakuJa/BYBE-DB/issues/2
